version: '3.8'

services:
  db:
    image: mysql:8.0 #เพื่อความทันสมัย (หรือใช้5.7 ตามเดิมได้หากต้องการ)
    container_name: mysql_db_700
    #MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ client รุ่นเก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8700:3306"
    volumes:
      - mysql_data_700:/var/lib/mysql
    networks:
      - weblab700
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_700
    environment:
      PMA_HOST: db #ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M #เ เพิ่มลิมิตการอัปโหลดไฟล์ SQL
    ports:
      - "8701:80"
    depends_on:
      - db
    networks:
      - weblab700
    restart: always 

networks:
  weblab700:
    driver: bridge

volumes:
  mysql_data_700:
    driver: local